# http://www.ros.org/wiki/base_local_planner

TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  escape_vel: -0.1
  holonomic_robot: true
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false
  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  controller_frequency: 20.0
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  simple_attractor: false
  publish_cost_grid_pc: true
  global_frame: /map
  oscillation_reset_dist: 0.05
  prune_plan: true
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  trans_stopped_velocity: 0.1
  rot_stopped_velocity: 0.1
  cost_scaling_factor: 10.0
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_scaling_factor: 0.2
  min_scaling_factor: 0.01
  clearing_radius: 0.6
  obstacle_range: 2.5
  raytrace_range: 3.0
